### PR TITLE
Fix readme for non-Windows camera search

### PR DESCRIPTION
**Pull request by patricktokeeffe**
The `arp` command is for inspecting cached ARP data. It does not search the network and will not help users locate a new camera on their network. 

Instead, use an open-source, cross-platform IP scanner if the StarDot Tools are not available.

### CODE REVIEW

**Comment by khufkens** [comment]
ARP tables can be updated by a ping call to the whole LAN. most of the time this will be:

```
ping 192.168.0.255
```

The latter doesn't require the installation of complex software which most won't understand. I'm also reluctant to suggest people to use software that might land them in trouble with IT.

In general, it seems that normal network services update the table quick enough for most, as we haven't had any issues.

**Comment by patricktokeeffe** [comment]
That approach is still incomplete:

* your `ping` command will not produce any results because it's missing the `-b` flag (maybe on Mac but not on Linux)
* the assumption users will know the correct network broadcast address is not fair

> The latter doesn't require the installation of complex software which most won't understand. I'm also reluctant to suggest people to use software that might land them in trouble with IT.

I'm saying that double-clicking a .deb file and using a GUI program is less complex than following a set of (incomplete) command terminal instructions. And the warning I included applies equally to both approaches.

**Comment by khufkens** [comment]
In over 500 camera installs I've yet to come across issues with the `arp -a` approach. While all other issues reside with people punching in the wrong details on the command line. The reason why this tool exists is that people could not follow instructions (with screenshots and that jazz) of how to setup the camera using the internal GUI! So, I don't think a GUI is a solution, ever in this sort of automation.

What could be done is writing a script, e.g. find_camera.sh. Which would:

- ping -b on a grep'ed broadcast address
- arp -a and filter on mac address
- return the matching IP

Which I'm pretty sure is all the StarDot Tools GUI does behind the scenes.

I would welcome such a contribution.

**Comment by patricktokeeffe** [comment]
I tried and failed first time with the `arp -a` approach for the reasons already reported. I've done this before and I'm just retracing steps, filling in missing instructions where needed. Most people will use StarDot tools but if they choose to follow the Linux/Mac instructions they will appreciate having a complete step-by-step.

**Comment by patricktokeeffe** [comment]
@khufkens did you see the force-push revision? It's just 2 lines

**Comment by khufkens** [comment]
Sorry haven't kept track of things.

**Pull request merged**
